/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;

/**
 *
 * @author SCSM11
 */

import java.text.ParseException;
import javax.swing.JFrame;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JTextArea;



public class DisplayNews extends javax.swing.JFrame {
  
    private List<NewsFilter.NewsArticle> fileNewsList ;
    private List<NewsFilter.NewsArticle> apiNewsList;

    /**
     * Creates new form DisplayNews
     */
    public DisplayNews(List<NewsFilter.NewsArticle> fileNewsList, List<NewsFilter.NewsArticle> apiNewsList){
        this.fileNewsList = fileNewsList;
        this.apiNewsList = apiNewsList;
        initComponents();
        displayNews();
    }
        
    private void displayNews(){
        StringBuilder fileNewsText = new StringBuilder();
        StringBuilder apiNewsText = new StringBuilder();
        
         if (fileNewsList != null && !fileNewsList.isEmpty()) {
         int count = Math.min(fileNewsList.size(), 5);
            for (int i = 0; i < count; i++) {
                NewsFilter.NewsArticle news = fileNewsList.get(i);
                fileNewsText.append(news.title).append("\n").append(news.url).append("\n")
                        .append(new SimpleDateFormat("dd MMM yyyy", Locale.ENGLISH).format(news.date)).append("\n\n");
            }
            setJTextAreaText(fileNewsText.toString(),jTextArea1);
        } else {
            System.out.println("NewsList is null. Cannot display news.");
        }
    
        if(apiNewsList != null && !apiNewsList.isEmpty()){
            int count = Math.min(apiNewsList.size(),5);
            for (int i =0; i<count; i++){
                NewsFilter.NewsArticle news = apiNewsList.get(i);
                apiNewsText.append(news.title).append("\n").append(news.url).append("\n")
                        .append(new SimpleDateFormat("dd MMM yyyy", Locale.ENGLISH).format(news.date)).append("\n\n");
            }
            setJTextAreaText(apiNewsText.toString(),API);
        }else {
            System.out.println("API NewsList is null or empty. Cannot display news.");
        }
        }
     private void setJTextAreaText(String text, javax.swing.JTextArea targetTextArea){
         targetTextArea.setText(text);
     }
    
    
  
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        API = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 420));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOP 5 NEWS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 50));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("REAL NEWS");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 250, 50));

        API.setBackground(new java.awt.Color(255, 204, 255));
        API.setColumns(20);
        API.setRows(5);
        jScrollPane2.setViewportView(API);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 310, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\LAVENDER.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

     

 
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayNews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new DisplayNews(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea API;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
