/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;

/**
 *
 * @author SCSM11
 */
import java.awt.Color;
import java.sql.Date;

public class Home extends javax.swing.JFrame {
    private String name;
    private Date date;
    private Trivia triviaFrame;
    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
        info.setBackground(new Color(255, 255, 255, 200));
        info.setOpaque(false);
    }
    @Override
    public void setName(String name) {
    this.name = name;
}

    public void setDate1(Date date) {
    this.date = date;
}

    /**
     *
     * @param triviaFrame
     */
    public void setTriviaFrame(Trivia triviaFrame){
        this.triviaFrame = triviaFrame;
    }
     
    public void setUser(String name) {
        user.setText(name);
    }
    public void setDate (Date date){
        Date.setText(date.toString()); }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewSection = new javax.swing.JButton();
        DailyTrivia = new javax.swing.JButton();
        PointShop = new javax.swing.JButton();
        info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        LOGOUT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Homepage");
        setPreferredSize(new java.awt.Dimension(725, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewSection.setBackground(new java.awt.Color(162, 178, 189));
        NewSection.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        NewSection.setForeground(new java.awt.Color(255, 255, 255));
        NewSection.setText("NEWS SECTION");
        NewSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSectionActionPerformed(evt);
            }
        });
        getContentPane().add(NewSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 230, 70));

        DailyTrivia.setBackground(new java.awt.Color(116, 127, 137));
        DailyTrivia.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        DailyTrivia.setForeground(new java.awt.Color(255, 255, 255));
        DailyTrivia.setText("Daily Trivia");
        DailyTrivia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyTriviaActionPerformed(evt);
            }
        });
        getContentPane().add(DailyTrivia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 230, 60));

        PointShop.setBackground(new java.awt.Color(87, 96, 111));
        PointShop.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        PointShop.setForeground(new java.awt.Color(255, 255, 255));
        PointShop.setText("POINT SHOP");
        getContentPane().add(PointShop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 230, 60));

        info.setBackground(new java.awt.Color(255, 255, 255 80));
        info.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CODE FOR");

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NATURE");

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USERNAME :");
        jLabel5.setToolTipText("");

        user.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("USERNAME");
        user.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Registration Date");

        Date.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Date.setText("Registration Date");

        LOGOUT.setBackground(new java.awt.Color(204, 204, 204));
        LOGOUT.setForeground(new java.awt.Color(0, 0, 0));
        LOGOUT.setText("LOGOUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(infoLayout.createSequentialGroup()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user)
                            .addComponent(Date)))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(LOGOUT)))
                .addGap(11, 11, 11))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\SCSM11\\Downloads\\stars night 2.0.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 970, 590));

        setSize(new java.awt.Dimension(982, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        // TODO add your handling code here:
        login LoginFrame = new login();
        LoginFrame.setVisible(true);
        LoginFrame.pack ();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void DailyTriviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyTriviaActionPerformed
        // TODO add your handling code here:
        if(triviaFrame != null){
            triviaFrame.showTrivia();
        }else{
            System.out.println("The frame is null");
        }
              
       
       
    }//GEN-LAST:event_DailyTriviaActionPerformed

    private void NewSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSectionActionPerformed
        NewsSection NewsSectionFrame = new NewsSection();
        NewsSectionFrame.setVisible(true);
        NewsSectionFrame.pack ();
        NewsSectionFrame.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_NewSectionActionPerformed
  
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DailyTrivia;
    private javax.swing.JLabel Date;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton NewSection;
    private javax.swing.JButton PointShop;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
